version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    expose:
      - '5672'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 60s
      timeout: 5s

  gateway:
    image: cordislib/gateway:0.2.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      CORDIS_AMQP_HOST: "amqp://rabbitmq:5672"
    depends_on:
      - rabbitmq

  bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      CORDIS_AMQP_HOST: "amqp://rabbitmq:5672"
    depends_on:
      - rabbitmq
      - gateway
